channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch::pytorch-cuda=11.7
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch=1.13
  - matplotlib
  - ipykernel
  - numpy
  - scipy
  - pylint
  - mypy
  - cython
  - pip
  - scikit-image
  - tqdm
  - attrs
  - gitpython
  - nbconvert
  - tabulate
  - black
  - isort
  - certifi
  - pip:
    - tifffile
    - nibabel
    - antspyx
    - intensity-normalization==2.2.3
